providers = ["java"]

[variables]
JAVA_VERSION = "21"

[phases.build]
cmds = [
    "chmod +x gradlew",
    "./gradlew clean build -x check -x test"
]

[phases.start]
cmd = "java -jar build/libs/portfolio-tracker-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
